import {
  EmptyState,
  ErrorState,
  LoadingState,
} from "../../../components/feedback/States";
import { Badge } from "../../../components/ui/Badge";
import { Card } from "../../../components/ui/Card";
import type { IndexedDocumentSummary } from "../../documents/types";
import type { AnswerSummary, GroundedAnswerResponse } from "../types";
import { CitationList } from "./CitationList";
import { SourceCard } from "./SourceCard";

type AnswerPanelProps = {
  response: GroundedAnswerResponse | null;
  summary: AnswerSummary | null;
  isAsking: boolean;
  errorMessage: string | null;
  selectedSource: number | null;
  documents: IndexedDocumentSummary[];
  onSelectSource: (sourceNumber: number) => void;
};

function paragraphs(text: string) {
  return text.split(/\n{2,}/).filter(Boolean);
}

export function AnswerPanel({
  response,
  summary,
  isAsking,
  errorMessage,
  selectedSource,
  documents,
  onSelectSource,
}: AnswerPanelProps) {
  if (!response && isAsking) {
    return <LoadingState label="Generating grounded answer..." />;
  }
  if (!response && errorMessage) {
    return <ErrorState title="Answer failed" description={errorMessage} />;
  }
  if (!response) {
    return (
      <EmptyState
        title="No answer yet"
        description="Ask a question to retrieve evidence and generate a cited answer."
      />
    );
  }

  return (
    <div className="space-y-4" aria-live="polite">
      <Card className={response.insufficient_context ? "border-warning/30" : ""}>
        <div className="flex flex-wrap gap-2">
          <Badge tone={response.insufficient_context ? "warning" : "success"}>
            {response.insufficient_context ? "Not enough evidence" : "Grounded answer"}
          </Badge>
          <Badge tone="neutral">{response.citations.length} citations</Badge>
          <Badge tone="neutral">{response.context_source_count} sources</Badge>
          <Badge tone="neutral">
            {summary?.documentFilterCount ?? 0} document filters
          </Badge>
          <Badge tone="neutral">
            {summary?.contentTypeFilterCount ?? 0} content-type filters
          </Badge>
          {summary?.durationMs !== null && summary?.durationMs !== undefined && (
            <Badge tone="neutral">
              {summary.durationMs} ms client-observed duration
            </Badge>
          )}
          {summary?.requestId && (
            <Badge tone="neutral">Request {summary.requestId}</Badge>
          )}
        </div>

        {response.insufficient_context && (
          <div className="mt-4 rounded-token border border-warning/30 bg-background p-4 text-sm text-muted">
            The system declined to generate an unsupported answer. Broaden filters or
            upload relevant documents, then ask again.
          </div>
        )}

        <section aria-labelledby="answer-heading" className="mt-5">
          <h2 id="answer-heading" className="font-semibold">
            Answer
          </h2>
          <div className="mt-3 space-y-3 text-sm leading-6 text-secondary">
            {paragraphs(response.answer).map((paragraph, index) => (
              <p key={index} className="whitespace-pre-wrap">
                {paragraph}
              </p>
            ))}
          </div>
        </section>

        <p className="mt-5 text-xs text-muted">
          Answers are generated by the backend provider configured for this environment.
          {response.model_name ? ` Provider output: ${response.model_name}.` : ""}
        </p>
        {response.finish_reason && (
          <p className="mt-1 text-xs text-muted">
            Finish reason: {response.finish_reason}
          </p>
        )}
      </Card>

      <Card>
        <CitationList
          citations={response.citations}
          markers={response.citation_markers}
          selectedSource={selectedSource}
          onSelect={onSelectSource}
        />
      </Card>

      <section aria-labelledby="source-cards-heading" className="space-y-3">
        <h2 id="source-cards-heading" className="text-lg font-semibold">
          Source evidence
        </h2>
        {response.citations.length === 0 ? (
          <EmptyState
            title="No source records"
            description="No citation sources were returned for this response."
          />
        ) : (
          response.citations.map((citation) => (
            <SourceCard
              key={`${citation.source_number}-${citation.chunk_id}`}
              citation={citation}
              documents={documents}
              selected={selectedSource === citation.source_number}
            />
          ))
        )}
      </section>

      {errorMessage && (
        <ErrorState title="Latest retry failed" description={errorMessage} />
      )}
    </div>
  );
}
